@contentType = application/json

###
# Create a new user
POST http://localhost:8886/users HTTP/1.1
Content-Type: {{contentType}}

{
      "name": "Jenny Doe",
      "profilePic": "",
      "displayName": "jenny",
      "phone": "91001223333",
      "password": "password",
      "currentLimit": "0"
}

###
# Update a user
PATCH http://localhost:8886/users/5 HTTP/1.1
Content-Type: {{contentType}}

{
      "name": "Jenny Doe Two"
}

###
# Delete a user
DELETE http://localhost:8886/users/7 HTTP/1.1
Content-Type: {{contentType}}